spring:
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password: sa
    driverClassName: org.h2.Driver

  data:
    jpa:
      repositories:
        bootstrap-mode: default
  jpa:
    hibernate:
      ddl-auto: create-drop


server:
  port: 8080
  address: 0.0.0.0